sudo cp *.a /mnt/kxvol
sudo cp ./ls/ls.a /mnt/kxvol
sudo cp ./chmod/chmod.a /mnt/kxvol
sudo cp ./copy/copy.a /mnt/kxvol
sudo cp ./dynloader/loader.elf /mnt/kxvol
sudo cp ./cat/cat.a /mnt/kxvol
sudo cp ./echo/echo.a /mnt/kxvol
sudo cp ./mkdir/mkdir.a /mnt/kxvol
sudo cp ./date/date.a /mnt/kxvol
sudo cp ./pwd/pwd.a /mnt/kxvol