sudo cp ./ls/ls.a /mnt/kxvol/bin/ls
sudo cp ./chmod/chmod.a /mnt/kxvol/bin/chmod
sudo cp ./copy/copy.a /mnt/kxvol/bin/cp
sudo cp ./dynloader/loader.elf /mnt/kxvol
sudo cp ./cat/cat.a /mnt/kxvol/bin/cat
sudo cp ./echo/echo.a /mnt/kxvol/bin/echo
sudo cp ./mkdir/mkdir.a /mnt/kxvol/bin/mkdir
sudo cp ./date/date.a /mnt/kxvol/bin/date
sudo cp ./pwd/pwd.a /mnt/kxvol/bin/pwd
sudo cp ./mv/mv.a /mnt/kxvol/bin/mv
sudo cp ./rm/rm.a /mnt/kxvol/bin/rm
sudo cp ./rmdir/rmdir.a /mnt/kxvol/bin/rmdir
sudo cp ./netctl/netctl.a /mnt/kxvol/bin/netctl
sudo cp ./kill/kill.a /mnt/kxvol/bin/kill
sudo cp ./rxsh/rxsh.a /mnt/kxvol
sudo cp ./env/env.a /mnt/kxvol/bin/env
sudo cp ./shutdown/shutdown.a /mnt/kxvol/bin/shutdown
sudo cp ./modctl/modctl.a /mnt/kxvol/bin/modctl
sudo cp ./route/route.a /mnt/kxvol/bin/route
sudo cp ./ln/ln.a /mnt/kxvol/bin/ln
sudo cp ./ping/ping.a /mnt/kxvol/bin/ping
sudo cp ./traceroute/traceroute.a /mnt/kxvol/bin/traceroute
sudo cp ./sysinfo/sysinfo.a /mnt/kxvol/bin/sysinfo
sudo cp ./clear/clear.a /mnt/kxvol/bin/clear
sudo cp ./mount/mount.a /mnt/kxvol/bin/mount
sudo cp ./readlink/readlink.a /mnt/kxvol/bin/readlink
sudo cp ./nslookup/nslookup.a /mnt/kxvol/bin/nslookup
sudo cp ./dhcl/dhcl.a /mnt/kxvol/bin/dhcl
sudo cp ./stty/stty.a /mnt/kxvol/bin/stty
sudo cp ./stat/stat.a /mnt/kxvol/bin/stat
sudo cp ./touch/touch.a /mnt/kxvol/bin/touch

sudo cp ./sudo/sudo.a /mnt/kxvol/bin/sudo
sudo chmod u+s /mnt/kxvol/bin/sudo
sudo chmod g+s /mnt/kxvol/bin/sudo