sudo cp ./ls/ls /mnt/kxvol/bin
sudo cp ./chmod/chmod.a /mnt/kxvol/bin
sudo cp ./copy/copy.a /mnt/kxvol
sudo cp ./dynloader/loader.elf /mnt/kxvol
sudo cp ./cat/cat.a /mnt/kxvol
sudo cp ./echo/echo.a /mnt/kxvol
sudo cp ./mkdir/mkdir.a /mnt/kxvol
sudo cp ./date/date.a /mnt/kxvol
sudo cp ./pwd/pwd.a /mnt/kxvol/bin
sudo cp ./mv/mv.a /mnt/kxvol/bin
sudo cp ./rm/rm.a /mnt/kxvol/bin
sudo cp ./rmdir/rmdir.a /mnt/kxvol/bin
sudo cp ./netctl/netctl.a /mnt/kxvol/bin
sudo cp ./kill/kill.a /mnt/kxvol/bin
sudo cp ./rxsh/rxsh.a /mnt/kxvol
sudo cp ./env/env.a /mnt/kxvol/bin
sudo cp ./shutdown/shutdown.a /mnt/kxvol/bin
sudo cp ./modctl/modctl.a /mnt/kxvol/bin

sudo cp ./sudo/sudo /mnt/kxvol/bin
sudo chmod u+s /mnt/kxvol/bin/sudo
sudo chmod g+s /mnt/kxvol/bin/sudo